# Generated by Django 5.1 on 2024-09-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image_url', models.URLField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
