# Generated by Django 5.1 on 2024-10-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='filmes_imagens/')),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
