# Generated by Django 5.1.2 on 2024-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filme_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
