# Generated by Django 5.1.2 on 2024-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filme_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='id_filme_tmdb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
